name: flutter_device_platform_id
description: "Flutter plugin for stable platform-scoped device IDs."
version: 1.0.1

repository: https://github.com/cyberprophet/flutter-device-unique-id

homepage: https://pub.dev/packages/flutter_device_platform_id

maintainer: ShareInvest Corp.

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shareinvest.flutter_device_platform_id
        pluginClass: FlutterDevicePlatformIdPlugin
      ios:
        pluginClass: FlutterDevicePlatformIdPlugin
      macos:
        pluginClass: FlutterDevicePlatformIdPlugin
      windows:
        pluginClass: FlutterDevicePlatformIdPlugin
      web:
        pluginClass: FlutterDevicePlatformIdWeb
        fileName: flutter_device_platform_id_web.dart
